# build pipeline: adf-workshop-ci

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - adf-iac
    - adf-code/publish_config.json

pool:
  vmImage: 'ubuntu-latest'

variables:
  adfId: 'ADF_AZURE_ID' # Replace this with your ADF ID.
  buildArtifact: 'ADF_ARM_Templates'

stages:
- stage: BuildAndValidate
  jobs:
  - job: Build
    steps:
      - task: UseNode@1
        inputs:
          version: '18.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.Repository.LocalPath)/adf-code' 
          verbose: true
        displayName: 'Install npm package'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.Repository.LocalPath)/adf-code'
          customCommand: 'run build validate $(Build.Repository.LocalPath)/adf-code $(adfId)'
        displayName: 'Validate'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.Repository.LocalPath)/adf-code'
          customCommand: 'run build export $(Build.Repository.LocalPath)/adf-code $(adfId) $(buildArtifact)'
        displayName: 'Validate and Generate ARM template'
      
      - script: 'ls -r $(Build.Repository.LocalPath)/adf-code'
        displayName: 'List Build Files'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)/adf-code/$(buildArtifact)' 
          artifact: '$(buildArtifact)'
          publishLocation: 'pipeline'